# Generated by Django 5.1.2 on 2024-11-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='deleted_flag',
            field=models.BooleanField(default=False),
        ),
    ]
