# Generated by Django 5.1.2 on 2024-10-22 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0002_create_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookcopy')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(auto_now_add=True)),
                ('reservation_end_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookcopy')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.user')),
            ],
        ),
    ]
