# Generated by Django 5.1.2 on 2024-11-11 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_edition_deleted_flag'),
        ('loans', '0004_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='books.bookcopy'),
        ),
    ]
