# Generated by Django 5.1.2 on 2024-11-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loan_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
